# Generated by Django 5.0.3 on 2026-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbooking',
            name='room',
            field=models.CharField(max_length=100),
        ),
    ]
