# Generated by Django 5.0.3 on 2026-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_guestbooking_options_guestbooking_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('single', 'Single Room'), ('twin', 'Twin Room'), ('standard', 'Standard Room'), ('family', 'Family Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite Room'), ('superior', 'Superior Room'), ('executive', 'Executive Room'), ('seaview', 'Sea View Suite'), ('penthouse', 'Penthouse Room')], max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('check_in_date', models.DateField()),
                ('guests', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
