# Generated by Django 5.0.3 on 2026-04-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbooking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
