# Generated by Django 5.0.3 on 2026-05-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
    ]
