# Generated by Django 4.2.30 on 2026-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notification',
            field=models.CharField(blank=True, help_text='A notification message for the guest after confirmation or checkout.', max_length=255, null=True),
        ),
    ]
